kind = "web"
previewPath = "/studio"
title = "Sanity Studio"
version = "1.0.0"
id = "primeaxis-studio"

[[services]]
localPort = 3333
name = "Sanity Studio"
paths = ["/studio"]

[services.development]
run = "npm run dev"

[services.production]

[services.production.run]
args = ["npm", "run", "start"]

[services.production.run.env]
PORT = "3333"
